In [1]:
from sklearn.metrics.pairwise import cosine_similarity
 
import tensorflow_hub as hub
import tensorflow as tf
 
elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)
 
 

In [7]:
import numpy as np

In [2]:
def elmo_vectors(x):
   
  embeddings=elmo(x, signature="default", as_dict=True)["elmo"]
  
  with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.tables_initializer())
    # return average of ELMo features
    return sess.run(tf.reduce_mean(embeddings,1))

In [3]:
corpus=["I'd like an apple juice",
                            "An apple a day keeps the doctor away",
                             "Eat apple every day",
                             "We buy apples every week",
                             "We use machine learning for text classification",
                             "Text classification is subfield of machine learning"]


In [4]:
elmo_embeddings=[]
print (len(corpus))
for i in range(len(corpus)):
    print (corpus[i])
    elmo_embeddings.append(elmo_vectors([corpus[i]])[0])
   


6
I'd like an apple juice
INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


An apple a day keeps the doctor away
INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


Eat apple every day
INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


We buy apples every week
INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


We use machine learning for text classification
INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


Text classification is subfield of machine learning
INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


In [5]:
print ( elmo_embeddings)
print(cosine_similarity(elmo_embeddings, elmo_embeddings))

[array([ 0.02739543, -0.10040519,  0.12195778, ..., -0.06023914,
        0.19663575,  0.38090163], dtype=float32), array([ 0.08833799, -0.21392673, -0.09389038, ..., -0.04924488,
        0.08270943,  0.25595036], dtype=float32), array([ 0.45237523, -0.00928466,  0.5245861 , ...,  0.00988377,
       -0.03330071,  0.25460476], dtype=float32), array([-0.14745471, -0.25623208,  0.20231596, ..., -0.11443622,
       -0.03759009,  0.18829295], dtype=float32), array([-0.4455993 , -0.14292821, -0.3249763 , ...,  0.01917106,
       -0.29726115, -0.02022681], dtype=float32), array([-0.25027984,  0.09800237, -0.10265853, ..., -0.22239093,
        0.2981895 ,  0.00978716], dtype=float32)]
[[1.         0.60986406 0.57428706 0.5386384  0.3963817  0.35737064]
 [0.60986406 1.         0.6036071  0.58240044 0.3964879  0.39825177]
 [0.57428706 0.6036071  0.9999997  0.7760986  0.38584024 0.33461636]
 [0.5386384  0.58240044 0.7760986  0.9999997  0.49227896 0.35490626]
 [0.3963817  0.3964879  0.38584024 0.49

In [8]:
sim=np.array(cosine_similarity(elmo_embeddings, elmo_embeddings))


In [14]:
pairwise_similarities=cosine_similarity(elmo_embeddings)

In [16]:
print(pairwise_similarities)

[[1.         0.60986406 0.57428706 0.5386384  0.3963817  0.35737064]
 [0.60986406 1.         0.6036071  0.58240044 0.3964879  0.39825177]
 [0.57428706 0.6036071  0.9999997  0.7760986  0.38584024 0.33461636]
 [0.5386384  0.58240044 0.7760986  0.9999997  0.49227896 0.35490626]
 [0.3963817  0.3964879  0.38584024 0.49227896 0.9999998  0.73076516]
 [0.35737064 0.39825177 0.33461636 0.35490626 0.73076516 1.0000002 ]]


In [18]:
max_sim=[]

for i in range(len(corpus)):
    similar_ix=np.argsort(sim[i])[::-1]
    max=sim[i][similar_ix[0]]
    max_sim.append(max)
    

In [19]:
max_sim

[1.0, 1.0, 0.9999997, 0.9999997, 0.9999998, 1.0000002]

In [20]:
total_sim=np.sum(max_sim,dtype=np.float32)

In [21]:
print("Final Similarity:", total_sim/len(corpus))
print ("Similarity % = ", 100*total_sim/len(corpus))


Final Similarity: 1.0
Similarity % =  100.0
