In [1]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('bert-base-nli-mean-tokens')

Some weights of the model checkpoint at C:\Users\HP/.cache\torch\sentence_transformers\sbert.net_models_bert-base-nli-mean-tokens\0_BERT were not used when initializing BertModel: ['classifier.bias', 'classifier.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [2]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [3]:
corpus=["I'd like an apple juice",
                            "An apple a day keeps the doctor away",
                             "Eat apple every day",
                             "We buy apples every week",
                             "We use machine learning for text classification",
                             "Text classification is subfield of machine learning"]



In [4]:
embeddings = model.encode(corpus)

In [5]:
embeddings.shape

(6, 768)

In [6]:
print(cosine_similarity(embeddings,embeddings))

[[0.9999998  0.49035358 0.6170854  0.49801618 0.33099023 0.2655072 ]
 [0.49035358 0.99999994 0.6176969  0.5870243  0.23409888 0.18803114]
 [0.6170854  0.6176969  1.0000002  0.8734125  0.20606458 0.14495446]
 [0.49801618 0.5870243  0.8734125  1.0000002  0.22751006 0.16931042]
 [0.33099023 0.23409888 0.20606458 0.22751006 0.9999997  0.93407905]
 [0.2655072  0.18803114 0.14495446 0.16931042 0.93407905 1.        ]]


In [18]:
sim=np.array(cosine_similarity(embeddings,embeddings))


In [11]:
pairwise_similarities=cosine_similarity(embeddings)

In [20]:
print(pairwise_similarities)

[[0.9999998  0.49035358 0.6170854  0.49801618 0.33099023 0.2655072 ]
 [0.49035358 0.99999994 0.6176969  0.5870243  0.23409888 0.18803114]
 [0.6170854  0.6176969  1.0000002  0.8734125  0.20606458 0.14495446]
 [0.49801618 0.5870243  0.8734125  1.0000002  0.22751006 0.16931042]
 [0.33099023 0.23409888 0.20606458 0.22751006 0.9999997  0.93407905]
 [0.2655072  0.18803114 0.14495446 0.16931042 0.93407905 1.        ]]


In [13]:
max_sim=[]

for i in range(len(corpus)):
    similar_ix=np.argsort(sim[i])[::-1]
    max=sim[i][similar_ix[0]]
    max_sim.append(max)
    

In [14]:
max_sim

[0.9999998, 0.99999994, 1.0000002, 1.0000002, 0.9999997, 1.0]

In [15]:
total_sim=np.sum(max_sim,dtype=np.float32)


In [17]:
print("Final Similarity:", total_sim/len(corpus))
print ("Similarity % = ", 100*total_sim/len(corpus))

Final Similarity: 0.9999999205271403
Similarity % =  99.99999205271403
